ignore:
  - vulnerability: CVE-2025-3277 #  sqlite-libs 3.48.0-r2
  - vulnerability: CVE-2024-9410 # ada-libs 2.9.2-r1
  - vulnerability: GHSA-4hjh-wcwx-xvwj # axios 1.8.2
  - vulnerability: CVE-2025-9230
  - vulnerability: CVE-2025-9231
  - vulnerability: CVE-2025-9232
  - vulnerability: GHSA-5j98-mcp5-4vw2 # glob 10.4.5
  - vulnerability: CVE-2025-60876 # busybox, ssl_client
  - vulnerability: CVE-2026-22184
    reason: "No fixes available as of 2026-01-14 on Dockerfile base image 22.21.1-alpine3.23"
  - vulnerability: CVE-2025-64718
    reason: "No fixes available as of 2026-01-14 on Dockerfile base image 22.21.1-alpine3.23"
  - vulnerability: "GHSA-8qq5-rm4j-mr97"
    package:
      name: "tar"
      versions: ["6.2.1", "7.4.3", "7.5.2"]
# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
