ignore:
  - vulnerability: CVE-2025-3277 #  sqlite-libs 3.48.0-r2
  - vulnerability: CVE-2024-9410 # ada-libs 2.9.2-r1
  - vulnerability: GHSA-4hjh-wcwx-xvwj # axios 1.8.2
  - vulnerability: CVE-2025-9230
  - vulnerability: CVE-2025-9231
  - vulnerability: CVE-2025-9232
  - vulnerability: GHSA-9965-vmph-33xx # validator 13.15.15


# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
