ignore:
  - vulnerability: CVE-2025-46394
  - vulnerability: CVE-2024-58251
  - vulnerability: CVE-2025-56200
    include-aliases: true


# Set output format defaults
output:
  - "table"
  - "json"

# Modify your CircleCI job to check critical count
search:
  scope: "squashed"
quiet: false
check-for-app-update: false
