## Add a TODO comment indicating the reason for each rejected dependency upgrade added to this list, and what should be done to resolve it (i.e. handle it through a story, etc).
reject: [
  ## v0.2.0 of the these libraries introduces various changes to base classes used in `private-shared-lib`.
  ## https://github.com/mojaloop/platform-shared-lib.
  ## Story to resolve issue: https://github.com/mojaloop/project/issues/2949
  '@mojaloop/platform-shared-lib-nodejs-kafka-client-lib',
  '@mojaloop/platform-shared-lib-messaging-types-lib',
  ## This should be removed and upgraded as part of this PR: https://github.com/mojaloop/sdk-scheme-adapter/pull/391
  '@mojaloop/api-snippets'
]
