## Add a TODO comment indicating the reason for each rejected dependency upgrade added to this list, and what should be done to resolve it (i.e. handle it through a story, etc).
reject: [
  ## Between version 0.2.15-0.2.21 there is a breaking change that results in a segmentation fault.
  ## TODO: Investigate.
  '@mojaloop/platform-shared-lib-nodejs-kafka-client-lib',
  ## TODO: The kafka connectivity is not working properly and the following update is causing service crash.
  '@mojaloop/logging-bc-client-lib',
  ## TODO: The new version of npm-check-updates uses new Glob v9.x and it is introducing a dependency Package "path-scurry@1.6.1" which is licensed under "BlueOak-1.0.0" which is not permitted by the Mojaloop License Policy
  npm-check-updates
]
