approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  - 1124334

npmMinimalAgeGate: 0

packageExtensions:
  "@mojaloop/central-services-shared@*":
    peerDependenciesMeta:
      "@mojaloop/central-services-error-handling":
        optional: true
      "@mojaloop/central-services-logger":
        optional: true
      "@mojaloop/central-services-metrics":
        optional: true
      "@mojaloop/event-sdk":
        optional: true
      ajv:
        optional: true
      ajv-formats:
        optional: true
      ajv-keyboards:
        optional: true
      ajv-keywords:
        optional: true
      knex:
        optional: true
      mysql2:
        optional: true
  eslint-plugin-jest@*:
    peerDependenciesMeta:
      typescript:
        optional: true

yarnPath: .yarn/releases/yarn-4.18.0.cjs
