openapi: 3.0.1
info:
  title: Mojaloop SDK Inbound Scheme Adapter API
  description: Mojaloop SDK Inbound Scheme Adapter API - To be implemented by DFSP backend
  license:
    name: Open API for FSP Interoperability (FSPIOP)
    url: http://www.majaloop.io
  version: 1.0.0

paths:
  /participants/{idType}/{idValue}:
    get:
      summary: Asks for the FSPID of the scheme participant that can handle transfers for the specified identifier type and value
      tags:
        - Participants
      parameters:
        - name: idType
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/idType'
        - name: idValue
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/idValue'
      responses:
        200:
          description: Response containing details of the requested party
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/participantsResponse'
        404:
          description: The party specified by the provided identifier type and value is not known to the server
        400:
          description: Malformed or missing required headers or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        500:
          description: An error occured processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /parties/{idType}/{idValue}:
    get:
      summary: Requests information relating to a transfer party identified by the specified identifier type and value
      tags:
        - Parties
      parameters:
        - name: idType
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/idType'
        - name: idValue
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/idValue'
      responses:
        200:
          description: Response containing details of the requested party
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transferParty'
        404:
          description: The party specified by the provided identifier type and value is not known to the server
        400:
          description: Malformed or missing required headers or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        500:
          description: An error occured processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /quoterequests:
    post:
      summary: Requests a quote for the specified transfer
      tags:
        - Quotes
      requestBody:
        description: Request for a transfer quotation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/quoteRequest'
      responses:
        200:
          description: A response to the transfer quotation request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/quoteResponse'
        400:
          description: Malformed or missing required headers or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        500:
          description: An error occured processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /transfers:
    post:
      summary: Transfers funds from an external account to an internal account
      tags:
        - Transfers
      requestBody:
        description: An incoming transfer request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/transferRequest'
      responses:
        200:
          description: The transfer was accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/transferResponse'
        400:
          description: Malformed or missing required headers or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        500:
          description: An error occured processing the request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

components:
  schemas:
  
    quoteRequest:
      type: object
      description: A request for a quote for transfer from the DFSP backend
      required:
        - quoteId
        - transactionId
        - to
        - from
        - amountType
        - amount
        - currency
        - transactionType
        - initiator
        - initiatorType
      properties:
        quoteId:
          $ref: '#/components/schemas/quoteId'
        transactionId:
          $ref: '#/components/schemas/transactionId'
          description: Identifier for the transaction, decided by the Payer FSP during the creation of the quote
        to:
          $ref: '#/components/schemas/transferParty'
          description: Information about the Payee in the proposed financial transaction.
        from:
          $ref: '#/components/schemas/transferParty'
          description: Information about the Payer in the proposed financial transaction.
        amountType:
          $ref: '#/components/schemas/amountType'
          description: 'SEND for send amount, RECEIVE for receive amount.'
        amount:
          $ref: '#/components/schemas/money'
          description: Depending on amountType. If SEND - The amount the Payer would like to send, that is, the amount that should be withdrawn from the Payer account including any fees. The amount is updated by each participating entity in the transaction. If RECEIVE - The amount the Payee should receive, that is, the amount that should be sent to the receiver exclusive any fees. The amount is not updated by any of the participating entities.
        currency:
          $ref: '#/components/schemas/currency'
        feesAmount:
          $ref: '#/components/schemas/money'
          description: The fees in the transaction. The fees element should be empty if fees should be non-disclosed. The fees element should be non-empty if fees should be disclosed.
        feesCurrency:
          $ref: '#/components/schemas/currency'
        transactionType:
          $ref: '#/components/schemas/transactionType'
          description: Type of transaction for which the quote is requested.
        initiator:
          $ref: '#/components/schemas/initiator'
          description: Specifies if the initiator of the transfer is the payer or payee
        initiatorType:
          $ref: '#/components/schemas/initiatorType'
          description: Specifies the type of the transaction initiator
        geoCode:
          $ref: '#/components/schemas/geoCode'
          description: Longitude and Latitude of the initiating Party. Can be used to detect fraud.
        note:
          type: string
          minLength: 1
          maxLength: 128
          description: An optional note associated with the requested transfer
        expiration:
          $ref: '#/components/schemas/timestamp'
          description: An optional deadline for responding to the quote request

    timestamp:
      type: string
      description: An ISO-8601 formatted timestamp
      pattern: ^(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:(\.\d{3}))(?:Z|[+-][01]\d:[0-5]\d)$

    dateOfBirth:
      type: string
      description: Date of birth in the form YYYY-MM-DD
      pattern: ^(?:[1-9]\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$

    initiator:
      type: string
      enum:
        - PAYER
        - PAYEE
        
    initiatorType:
      type: string
      enum:
        - CONSUMER
        - AGENT
        - BUSINESS
        - DEVICE
      
    quoteResponse:
      type: object
      description: A response to a request for a quote
      required:
        - quoteId
        - transactionId
        - transferAmount
        - transferAmountCurrency
      properties:
        quoteId:
          $ref: '#/components/schemas/quoteId'
          description: Id of the quote this response relates to
        transactionId:
          $ref: '#/components/schemas/transactionId'
          description: Identifier for the transaction, decided by the Payer FSP during the creation of the quote
        transferAmount:
          $ref: '#/components/schemas/money'
          description: The amount of money that the Payer FSP should transfer to the Payee FSP
        transferAmountCurrency:
          $ref: '#/components/schemas/currency'
          description: The currency of the transferAmount
        payeeReceiveAmount:  
          $ref: '#/components/schemas/money'
          description: The amount that the Payee should receive in the end-to-end transaction. Optional as the Payee FSP might not want to disclose any optional Payee fees
        payeeReceiveAmountCurrency:
          $ref: '#/components/schemas/currency'
          description: The currency of the payeeReceiveAmount
        payeeFspFeeAmount:
          $ref: '#/components/schemas/money'
          description: Payee FSP’s part of the transaction fee
        payeeFspFeeAmountCurrency:
          $ref: '#/components/schemas/currency'      
          description: The currency of the payeeFspFeeAmount
        payeeFspCommissionAmount:
          $ref: '#/components/schemas/money'
          description: Transaction commission from the Payee FSP
        payeeFspCommissionAmountCurrency:
          $ref: '#/components/schemas/currency'  
          description: Currency of the payeeFspCommissionAmount
        expiration:
          $ref: '#/components/schemas/timestamp'
          description: Timestamp specifying the validity period of the quotation
        geoCode:
          $ref: '#/components/schemas/geoCode'
          description: Longitude and Latitude of the Payee. Can be used to detect fraud
        
  
    participantsResponse:
      type: object
      properties:
        fspId:
          $ref: '#/components/schemas/fspId'
  
    fspId:
      type: string
      minLength: 1
      maxLength: 32
  
    payerType:
      type: string
      enum:
      - CONSUMER
      - AGENT
      - BUSINESS
      - DEVICE
      
    amountType:
      type: string
      enum:
      - SEND
      - RECEIVE
      
    transactionType:
      type: string
      enum:
      - TRANSFER
      
    transferRequest:
      type: object
      required:
        - transferId
        - quote
        - from
        - to
        - amountType
        - currency
        - amount
        - transactionType
      properties:
        transferId:
          $ref: '#/components/schemas/transferId'
        quote:
          $ref: '#/components/schemas/quoteResponse'
        from:
          $ref: '#/components/schemas/transferParty'
        to:
          $ref: '#/components/schemas/transferParty'
        amountType:
          $ref: '#/components/schemas/amountType'
        currency:
          $ref: '#/components/schemas/currency'
        amount:
          $ref: '#/components/schemas/money'
        transactionType:
          $ref: '#/components/schemas/transactionType'
        note:
          maxLength: 128
          type: string
          
    transferStatus:
      type: string
      enum:
      - ERROR_OCCURED
      - WAITING_FOR_QUOTE_ACCEPTANCE
      - COMPLETED
      
    idType:
      type: string
      enum:
      - MSISDN
      - ACCOUNT_NO
      
    idValue:
      type: string
      minLength: 1
      maxLength: 128
      
    money:
      pattern: ^([0]|([1-9][0-9]{0,17}))([.][0-9]{0,3}[1-9])?$
      type: string
      
    transferResponse:
      type: object
      required:
        - homeTransactionId
      properties:
        homeTransactionId:
          type: string
          description: Transaction ID from the DFSP backend, used to reconcile transactions between the switch and DFSP backend systems
          
    currency:
      maxLength: 3
      minLength: 3
      type: string
      
    transferId:
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
      type: string
      description: A Mojaloop API transfer identifier (UUID)
      
    quoteId:
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
      type: string
      description: A Mojaloop API quote identifier (UUID)
      
    transactionId:
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
      type: string
      description: ID of the transaction, the ID is decided by the Payer FSP during the creation of the quote
      
    transferParty:
      type: object
      required:
        - idType
        - idValue
      properties:
        type:
          $ref: '#/components/schemas/payerType'
        idType:
          $ref: '#/components/schemas/idType'
        idValue:
          type: string
          description: The identifier string used to identify the sender
        displayName:
          type: string
          description: Display name of the sender if known
        firstName:
          type: string
          description: Party first name
        middleName:
          type: string
          description: Party moddle name
        lastName:
          type: string
          description: Party last name
        dateOfBirth:
          $ref: '#/components/schemas/dateOfBirth'
        merchantClassificationCode:
          type: string
          description: Up to 4 digits specifying the senders merchant classification, if known and applicable
          
    geoCode:
      type: object
      description: Indicates the geographic location from where the transaction was initiated.
      properties:
        latitude:
          $ref: '#/components/schemas/latitude'
        longitude:
          $ref: '#/components/schemas/longitude'
      required:
        - latitude
        - longitude
        
    latitude:
      type: string
      pattern: ^(\+|-)?(?:90(?:(?:\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\.[0-9]{1,6})?))$
      description: The API data type Latitude is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons.
    longitude:
      type: string
      pattern: ^(\+|-)?(?:180(?:(?:\.0{1,6})?)|(?:[0-9]|[1-9][0-9]|1[0-7][0-9])(?:(?:\.[0-9]{1,6})?))$
      description: The API data type Longitude is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons.
          
    errorResponse:
      type: object
      properties:
        statusCode:
          type: string
          description: Error code as string
        message:
          type: string
          description: Error message text





